const authRoutes = require("./controllers/auth");
const auditLogRoutes = require("./controllers/auditLogs");
const clientRoutes = require("./controllers/clients");
const configRoutes = require("./controllers/config");
const dataRoutes = require("./controllers/data");
const notebookRoutes = require("./controllers/notebook");
const emailQueueRoutes = require("./controllers/queue");
const mailboxRoutes = require("./controllers/mailboxes");
const messageRoutes = require("./controllers/messages");
const roleRoutes = require("./controllers/roles");
const monitoringRoutes = require("./controllers/monitoring");
const objectStoreRoutes = require("./controllers/storage");
const ticketRoutes = require("./controllers/ticket");
const threadRoutes = require("./controllers/threads");
// const { router: emailRouter } = require('./lib/nodemailer/ticket/assigned');
const timeTrackingRoutes = require("./controllers/time");
const userRoutes = require("./controllers/users");
const webhookRoutes = require("./controllers/webhooks");
// const imapRoutes = require("../../lib/services/imap.service");
const { router: imapRouter } = require("./lib/services/imap.service");
const { router: smtpRouter } = require("./lib/services/smtp.service");
const phpBridgeRouter = require("./lib/services/phpBridge");
// const { router: emailRouter } = require('./lib/nodemailer/ticket/assigned');

function registerRoutes(app) {
   app.use("/api/v1/auth", authRoutes);
   app.use("/api/v1/audit-logs", auditLogRoutes);
   app.use("/api/v1/email-queue",emailQueueRoutes);
   app.use("/api/v1/mailboxes", mailboxRoutes);
   app.use("/api/v1/messages", messageRoutes);
   app.use("/api/v1/data",dataRoutes);
   app.use("/api/v1/ticket",ticketRoutes);
   app.use("/api/v1/threads", threadRoutes);
   app.use("/api/v1/user",userRoutes);
   app.use("/api/v1/notebook",notebookRoutes);
   app.use("/api/v1/client",clientRoutes);
   app.use("/api/v1/webhook",webhookRoutes);
   app.use("/api/v1/config/authentication",configRoutes);
   app.use("/api/v1/time",timeTrackingRoutes);
   app.use("/api/v1/storage",objectStoreRoutes);
   app.use("/api/v1/role",roleRoutes);
   app.use("/api/v1/monitoring", monitoringRoutes);
   app.use("/api/v1/imap",imapRouter);
   app.use("/api/v1/smtp",smtpRouter);
   app.use("/api/v1/php", phpBridgeRouter);
   // Backward-compatible aliases for legacy PHP integrations.
   app.use("/api/php", phpBridgeRouter);
   app.use("/php", phpBridgeRouter);
   // app.use('/api/v1/email', emailRouter);
}
module.exports = { registerRoutes };
